version: '3.4'

services:
  redis:
    container_name: redis_cache_store
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis_cache_store:/data
volumes:
  redis_cache_store:
    driver: local
